### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by HenrikNielsen** [sofasurfer/MODX-FormItLog#1]
Thanks for a useful extension to MODX!

When saving to CSV, there are some problems with characters that contain accents.

If the file is opened, in  Ecxel - then æøå becomes Ã | Ã ¸ Ã ¥

If I re-save it in a plain text editor with Byte Order Mark turned on, all are correct.

**Comment by sofasurfer** [comment]
Hi Henrik,

thanks for the feedback, I'm using Open Office and there the special characters are shown correctly in the CSV file.

Currently I don't have MS Excel installed but will look into this to check what causes this issue.

I guess it's the way the CSV file is stored/saved on the server.

When you look at the CSV file after downloading in a plain text editor, can you see the characters correctly?

**Comment by HenrikNielsen** [comment]
Hello Kilian,

When opening the file in fx. E-texteditor, there are no problems - it's only when opening it in Excel the problems arise.

I know that Mark had a similar problem with VersionX: https://github.com/Mark-H/VersionX/issues/26#issuecomment-3616149 - but I am afraid that I don't have a clue what the solution where.

**Comment by Mark-H** [comment]
In VersionX the issue was the encoding of the core files.

**Comment by sofasurfer** [comment]
I can't reproduce this anymore
